package vn.asiantech.android.springfinalweather.kotlin.`object`

class Constants {
    companion object {
        // const for Location permission
        const val LOCATION_PERMISSION = "location_permission"
        const val UNIT_OF_TEMP = "unit_of_temp"
        const val UNIT_OF_WIND_SPEED = "unit_of_wind_speed"
        const val LOCATION_PERMISSION_REQUEST = 1

        // const for Google find City Api
        const val BASE_URL_API_GOOGLE = "https://maps.googleapis.com"
        const val CITY_TYPES = "(cities)"
        const val GOOGLE_KEY = "AIzaSyAvt30-GCmebRk-RB4QOlljVrCnepnyMHA"

        //const for intent key
        const val CITY_NAME = "city_name"
        const val DATE = "date"
        const val COUNTRY_NAME = "country_name"
        const val TEMP = "temp"
        const val APPTEMP = "app_temp"
        const val SUNRISE = "sun_rise"
        const val SUNSET = "sunset"
        const val HUMIDITY = "humidity"
        const val WIND = "wind"
        const val CLOUD = "cloud"
        const val DESCRIPTION = "description"
        const val ICON = "icon"

        //const for OpenWeatherApi
        const val KEY = "2990381aeee141bf8d86abf206a60d76"
        const val BASE_URL = "https://api.weatherbit.io"
        const val DAYS = "5"

        //const for icon weather
        const val ICON_T01D = "t01d"
        const val ICON_T01N = "t01n"
        const val ICON_T02D = "t02d"
        const val ICON_T02N = "t02n"
        const val ICON_T03D = "t03d"
        const val ICON_T03N = "t03n"
        const val ICON_T04D = "t04d"
        const val ICON_T04N = "t04n"
        const val ICON_T05D = "t05d"
        const val ICON_T05N = "t05n"
        const val ICON_D01D = "d01d"
        const val ICON_D01N = "d01n"
        const val ICON_D02D = "d02d"
        const val ICON_D02N = "d02n"
        const val ICON_D03D = "d03d"
        const val ICON_D03N = "d03n"
        const val ICON_R01D = "r01d"
        const val ICON_R01N = "r01n"
        const val ICON_R02D = "r02d"
        const val ICON_R02N = "r02n"
        const val ICON_R03D = "r03d"
        const val ICON_R03N = "r03n"
        const val ICON_F01D = "f01d"
        const val ICON_F01N = "f01n"
        const val ICON_R04D = "r04d"
        const val ICON_R04N = "r04n"
        const val ICON_R05D = "r05d"
        const val ICON_R05N = "r05n"
        const val ICON_R06D = "r06d"
        const val ICON_R06N = "r06n"
        const val ICON_S01D = "s01d"
        const val ICON_S01N = "s01n"
        const val ICON_S02D = "s02d"
        const val ICON_S02N = "s02n"
        const val ICON_S03D = "s03d"
        const val ICON_S03N = "s03n"
        const val ICON_S04D = "s04d"
        const val ICON_S04N = "s04n"
        const val ICON_S05D = "s05d"
        const val ICON_S05N = "s05n"
        const val ICON_S06D = "s06d"
        const val ICON_S06N = "s06n"
        const val ICON_A01D = "a01d"
        const val ICON_A01N = "a01n"
        const val ICON_A02D = "a02d"
        const val ICON_A02N = "a02n"
        const val ICON_A03D = "a03d"
        const val ICON_A03N = "a03n"
        const val ICON_A04D = "a04d"
        const val ICON_A04N = "a04n"
        const val ICON_A05D = "a05d"
        const val ICON_A05N = "a05n"
        const val ICON_A06D = "a06d"
        const val ICON_A06N = "a06n"
        const val ICON_C01D = "c01d"
        const val ICON_C01N = "c01n"
        const val ICON_C02D = "c02d"
        const val ICON_C02N = "c02n"
        const val ICON_C03D = "c03d"
        const val ICON_C03N = "c03n"
        const val ICON_C04D = "c04d"
        const val ICON_C04N = "c04n"
        const val ICON_U00D = "u00d"
        const val ICON_U00N = "u00n"

        //const for State of City Collection
        const val USER_LOCATION = true
        const val OTHER_LOCATION = false
        const val FOCUS_POSITION = "focus_position"
    }
}
